name: Dispatch ServerlessPipeline

on:
  push:
    branches:
      - main

jobs:
  dispatch_lambda_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Serverless Commit Event
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            https://api.github.com/repos/fiap-9soat-snackbar/snackbar-pipeline/dispatches \
            -d '{"event_type":"lambda_commit","client_payload":{"repo_name":"serverless"}}'
